# Scuba related test files
load("//testing/web/build_defs:web.bzl", "custom_browser")

licenses(["notice"])

custom_browser(
    name = "chrome-linux",
    browser = "//testing/web/browsers:chrome-linux",
    metadata = ["chrome-linux-metadata.json"],
    visibility = ["//multitest_transport"],
)
